# Single-Topic Document Q&A with RAG

###Jade Webb

###Feb 2026

###References:
###RAG: https://www.kaggle.com/code/markishere/day-2-document-q-a-with-rag/notebook
###Dataset: https://www.kaggle.com/datasets/samuelmatsuoharris/single-topic-rag-evaluation-dataset/data

##Installations and Imports

In [1]:
pip install google-genai

Requirement already satisfied: google-genai in /usr/local/lib/python3.12/dist-packages (1.64.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.12.3)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.3.1)
Requirement already satisfied: aiohttp>=3.10.11 in /usr/local/lib/python3.12/dist-packages (from google-genai) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.10.11->google-genai) (1.22.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai) (0.6.2)

In [2]:
pip install chromadb

Collecting chromadb
  Downloading chromadb-1.5.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.4.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.41.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Collecting posthog<6.0.0,>=2.4.0 (from chromadb)
  Downloading posthog-5.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.24.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.0)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.72.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.39.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.39.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.39.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.60b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl.metadata (2.4 kB)
Collecting backoff>=1.10.0 (from posthog<6.0.0,>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog<6.0.0,>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9->chromadb) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.4.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.3.0)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (0.24.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.4)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Downloading chromadb-1.5.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 23.4 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 9.9 MB/s eta 0:00:00
Downloading build-1.4.0-py3-none-any.whl (24 kB)
Downloading kubernetes-35.0.0-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 36.0 MB/s eta 0:00:00
Downloading onnxruntime-1.24.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 23.9 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.39.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.39.1-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 2.8 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.39.1-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 4.2 MB/s eta 0:00:00
Downloading opentelemetry_api-1.39.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 2.2 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl (219 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 3.7 MB/s eta 0:00:00
Downloading posthog-5.4.0-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 3.3 MB/s eta 0:00:00
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 2.8 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.1 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, opentelemetry-proto, bcrypt, backoff, posthog, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, onnxruntime, build, opentelemetry-semantic-conventions, kubernetes, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.39.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.39.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.39.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.39.1 which is incompatible.
Successfully installed backoff-2.2.1 bcrypt-5.0.0 build-1.4.0 chromadb-1.5.2 durationpy-0.10 kubernetes-35.0.0 onnxruntime-1.24.2 opentelemetry-api-1.39.1 opentelemetry-exporter-otlp-proto-common-1.39.1 opentelemetry-exporter-otlp-proto-grpc-1.39.1 opentelemetry-proto-1.39.1 opentelemetry-sdk-1.39.1 opentelemetry-semantic-conventions-0.60b1 posthog-5.4.0 pybase64-1.4.3 pypika-0.51.1 pyproject_hooks-1.2.0

In [3]:
pip install langchain_openai

Collecting langchain_openai
  Downloading langchain_openai-1.1.10-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (1.2.15)
Requirement already satisfied: openai<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (2.23.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain_openai) (0.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (0.7.6)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain_openai) (0.14.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain_openai) (4.67.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2.32.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=2.20.0->langchain_openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain_openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain_openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain_openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain_openai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain_openai) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain_openai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain_openai) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain_openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain_openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain_openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain_openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain_openai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain_openai) (2.5.0)
Downloading langchain_openai-1.1.10-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 kB 2.3 MB/s eta 0:00:00
Installing collected packages: langchain_openai
Successfully installed langchain_openai-1.1.10

In [4]:
import getpass
import os
import pandas as pd
import chromadb
import ast

from google import genai
from google.genai import types
from IPython.display import Markdown
from chromadb import Documents, EmbeddingFunction, Embeddings
from google.api_core import retry
from google.genai import types

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

In [5]:
if not os.getenv("GOOGLE_API_KEY"):
    os.environ["GOOGLE_API_KEY"] = getpass.getpass("Enter your GOOGLE API key: ")

Enter your GOOGLE API key: ··········

In [6]:
if not os.getenv("OPENAI_API_KEY"):
    os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OPENAI API key: ")

Enter your OPENAI API key: ··········

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Load Gemini Client

In [8]:
client = genai.Client(api_key=os.environ["GOOGLE_API_KEY"])

In [9]:
#view available models
for m in client.models.list():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025

##Load and Inspect 3 Q&A Datasets

Single Passage: 40 Q&A pairs whose answers must be generated by analyzing a single passage in a single document.

Multi Passage: 40 Q&A pairs whose answers must be generated by analyzing multiple passages in a single document.

No Answer: 40 questions that do not have an answer within the documents.

In [10]:
#single passage
file_path = '/content/drive/MyDrive/Colab Notebooks/RAG/single_passage_answer_questions.csv'
single_df = pd.read_csv(file_path)

In [11]:
single_df.head()

,document_index,question,answer
0,0,What do keybullet kin drop?,Keybullet kin drop a key upon death.
1,0,What kind of gun does the bandana bullet kin use?,The bandana bullet kin wields a machine pistol.
2,1,What do the giants look like?,"One giant is burly, grey-skinned, and 20 feet ..."
3,1,What happens on day 2?,"After a few miles of winding tunnel, you emerg..."
4,2,What were the requirements for the project?,The tool had the following requirements:\n- Ch...

In [61]:
#replace inacccurate question
single_df.loc[2] = [1, "What creatures are encountered on day 4 and what do they want?", "A horde of kobolds are encountered. They demand food in the ambush."]
#clarify poor questions
single_df.loc[4] = [2, "What were the requirements for the STICI-Note project?", "The project had the following requirements:\n- Chatbot that you can ask questions and get answers in response (conversational memory is not required).\n- Information is taken from an unstructured text file.\n- It must be able to tell me if it doesn’t know the answer to my question.\n- Fast.\n- Efficient enough to run on my MacBook with other programs without any performance issues.\n- Locally run for privacy and to ensure it will always be free, runnable, and consistent."]
single_df.loc[5] = [2, "What data was used to test the STICI-Note prototype?", "Grace Hopper's Wikipedia page and Alan Turing's Wikipedia page were used to test the prototype."]
single_df.loc[6] = [3, "How do the data storage options for enterprise RAG Pipelines compare?", "For fast start: use SQLite3 and ChromaDB (File-based) out-of-the-box - no install required.\nFor speed + scale: use MongoDB (text collection) and Milvus (vector db) - install with Docker Compose\nFor postgres: use Postgres for both text collection and vector DB - install with Docker Compose\nFor mix-and-match: LLMWare supports 3 text collection databases (Mongo, Postgres, SQLite) and 10 vector databases (Milvus, PGVector-Postgres, Neo4j, Redis, Mongo-Atlas, Qdrant, Faiss, LanceDB, ChromaDB and Pinecone)."]
single_df.loc[10] = [5, "What are the key topics of the article about Data Science Impact?", "The key topics of this article are: \"why prioritizing impact matters not just for managers, but also ICs\"; \"why focusing on impact is hard\"; \"how to maximize your impact\"; and \"how to overcome common challenges in driving real impact\"."]
single_df.loc[35] = [17, "What year is Alan Wake 2 set?", "Alan Wake 2 is set in 2023, thirteen years after the events of Alan Wake."]
single_df.loc[37] = [18, "Who was resurrected with a group of other murder victims in the book?", "Lou was resurrected along with a handful of other women murdered by a single serial killer."]
single_df.loc[38] = [19, "What categories does Huang's paper split the RAG technique paradigm into?", "This paper organizes the RAG paradigm into four categories: pre-retrieval, retrieval, post-retrieval, and generation."]
single_df.loc[39] = [19, "In what way can including unrelated documents affect the RAG system in Huang's research?", "The inclusion of irrelevant documents can significantly improve accuracy."]

In [14]:
single_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   document_index  40 non-null     int64
 1   question        40 non-null     object
 2   answer          40 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.1+ KB

In [15]:
single_df.isnull().sum()

document_index    0
question          0
answer            0
dtype: int64

In [16]:
single_df.duplicated().sum()

np.int64(0)

In [17]:
#multi passage
file_path = '/content/drive/MyDrive/Colab Notebooks/RAG/multi_passage_answer_questions.csv'
multi_df = pd.read_csv(file_path)

In [18]:
multi_df.head()

,document_index,question,answer
0,0,Which enemy types wield an AK-47?,Assault-rifle wielding Bullet and Tankers wiel...
1,0,What makes jammed enemies different?,"Jammed Keybullet Kin drop 2 keys instead of 1,..."
2,1,What enemies are encountered in the second enc...,26 kobolds and 1 kobold inventor are encounter...
3,1,What monsters are encountered in this journey?,"Ropers, kobolds, kobold inventors, fire giants..."
4,2,What framework was chosen to execute the RAG p...,The LangChain framework was used to orchestrat...

In [19]:
#replace inacccurate question
multi_df.loc[3] = [1, "What smells are encountered in this journey?", "Smells of hard water, wet earth, and a rancid odor are encountered along the journey."]

In [20]:
multi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   document_index  40 non-null     int64
 1   question        40 non-null     object
 2   answer          40 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.1+ KB

In [21]:
multi_df.isnull().sum()

document_index    0
question          0
answer            0
dtype: int64

In [22]:
multi_df.duplicated().sum()

np.int64(0)

In [23]:
#no answer
file_path = '/content/drive/MyDrive/Colab Notebooks/RAG/no_answer_questions.csv'
no_df = pd.read_csv(file_path)

In [24]:
no_df.head()

   document_index                                          question
0               0  How much health does the Mutant Bullet Kin have?
1               0                       Where can bishops be found?
2               1                          What happened on day 10?
3               1                         What did the goblins say?
4               2      Why was the H100 GPU chosen for computation?

In [74]:
#clarify poor questions
no_df.loc[0] = [0, "How much health (numerical quantity) does the Mutant Bullet Kin have?"]
no_df.loc[29] = [14, "Who is Perry and Jackie's cousin?"]
no_df.loc[38] = [19, "Which paper by Hinton et. al. was used in Huang's paper?"]
no_df.loc[39] = [19, "Why was hardware such a limiting factor in Huang's research?"]

In [26]:
no_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   document_index  40 non-null     int64
 1   question        40 non-null     object
dtypes: int64(1), object(1)
memory usage: 772.0+ bytes

In [27]:
no_df.isnull().sum()

document_index    0
question          0
dtype: int64

In [28]:
no_df.duplicated().sum()

np.int64(0)

##Load and Inspect Documents Dataset

20 niche text documents (articles, blogs, documentation) produced within the last few years (as of July 2024), ranging from a few thousand to a few ten thousand words.

In [29]:
file_path = '/content/drive/MyDrive/Colab Notebooks/RAG/single_topic_rag_evaluation_documents.csv'
df = pd.read_csv(file_path)

In [30]:
df.head()

,index,source_url,text
0,0,https://enterthegungeon.fandom.com/wiki/Bullet...,Bullet Kin\nBullet Kin are one of the most com...
1,1,https://www.dropbox.com/scl/fi/ljtdg6eaucrbf1a...,---The Paths through the Underground/Underdark...
2,2,https://bytes-and-nibbles.web.app/bytes/stici-...,Semantic and Textual Inference Chatbot Interfa...
3,3,https://github.com/llmware-ai/llmware,llmware\n\nBuilding Enterprise RAG Pipelines w...
4,4,https://docs.marimo.io/recipes.html,Recipes\nThis page includes code snippets or “...

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       20 non-null     int64
 1   source_url  20 non-null     object
 2   text        20 non-null     object
dtypes: int64(1), object(2)
memory usage: 612.0+ bytes

In [32]:
df.isnull().sum()

index         0
source_url    0
text          0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

## Embedding Database
Perform document embedding using Gemini Embedding 001 and populate a Chroma database.

In [34]:
#retry embedding when per-minute limit is reached
is_retriable = lambda e: (isinstance(e, genai.errors.APIError) and e.code in {429, 503})

In [35]:
#generate document or query embeddings with Gemini API
class GeminiEmbeddingFunction(EmbeddingFunction):

    document_mode = True

    @retry.Retry(predicate=is_retriable)
    def __call__(self, input: Documents) -> Embeddings:
        if self.document_mode:  #generate embeddings for documents
            embedding_task = "retrieval_document"
        else:                   #generate embeddings for queries
            embedding_task = "retrieval_query"

        response = client.models.embed_content(
            model="models/gemini-embedding-001",
            contents=input,
            config=types.EmbedContentConfig(task_type=embedding_task),
        )
        return [e.values for e in response.embeddings]

In [36]:
embed_func = GeminiEmbeddingFunction()
#document mode
embed_func.document_mode = True

/tmp/ipython-input-652/1492628580.py:1: DeprecationWarning: The class GeminiEmbeddingFunction does not implement __init__. This will be required in a future version.
  embed_func = GeminiEmbeddingFunction()

In [37]:
chromadb_client = chromadb.Client()
db = chromadb_client.get_or_create_collection(name="single_topic_db", embedding_function=embed_func)

db.add(documents=list(df['text']), ids=[str(i) for i in range(len(df['text']))])

In [38]:
db.count()

20

##Retrieval and Generation
Perform RAG for all 3 Q&A datasets with Gemini 3 Flash.

In [77]:
single_queries = list(single_df['question'])
multi_queries = list(multi_df['question'])
no_queries = list(no_df['question'])

In [79]:
def RAG(queries):
  embed_func.document_mode = False
  answers = []
  for query in queries:
    result = db.query(query_texts=[query], n_results=2) #get 2 most relevant documents
    [all_passages] = result["documents"]

    prompt = f"""You are a helpful and informative bot that answers questions by only using text from the reference passage(s) included below.
    Do not rely on any other information.
    You must respond in complete sentences and be concise, including only the most relevant direct answer from the passage(s).
    If a passage is irrelevant to the answer, you may ignore it.
    The user has no knowledge of your use of passages or the passages themselves.
    Never mention passages in your response.
    If the answer is not found in the passages, your response must be limited to exactly the phrase 'I don't know'.
    Interpret each question strictly and literally.
    Each response must be specific. If you cannot produce a specific answer, say 'I don't know'.
    Never hallucinate, make up an answer, or make assumptions.

    QUESTION: {query}
    """

    for passage in all_passages:
      passage_oneline = passage.replace("\n", " ")
      prompt += f"PASSAGE: {passage_oneline}\n"

    answer = client.models.generate_content(
      model="gemini-3-flash-preview",
      contents=prompt)

    answers.append((answer.text))

  return answers

In [67]:
single_answers = RAG(single_queries)
single_answers

['Keybullet Kin drop a key upon death, while Jammed Keybullet Kin drop two keys.',
 'The Bandana Bullet Kin wields Machine Pistols.',
 'On day 4, twenty-six kobolds and one kobold inventor are encountered. These creatures want food and items, threatening to stab the group if they do not drop their things.',
 'On day 2, travelers emerge in a small grotto of stalactites and stalagmites and encounter two Ropers.',
 'The requirements for the STICI-Note project included a chatbot that can answer questions from an unstructured text file and state if it does not know an answer. Additionally, the tool needed to be fast, locally run for privacy and consistency, and efficient enough to run on a MacBook without performance issues.',
 'The STICI-Note prototype was tested using the Wikipedia pages of Grace Hopper and Alan Turing.',
 'Data storage options for enterprise RAG pipelines include SQLite3 and ChromaDB for file-based quick starts, MongoDB and Milvus for higher speed and scale, and Postgres for combined text and vector storage. These integrated data stores range from laptop-based systems to parallelized clusters and allow for mixing and matching between three text collection databases and ten vector databases.',
 "I don't know.",
 'To create a button, you can use `mo.ui.button()` or `mo.ui.run_button()`.',
 'You might use caching to store expensive intermediate computations, such as t-SNE, UMAP, or PyMDE embeddings, especially when a notebook runs cells automatically as code or UI elements change.',
 'The key topics of the article include why prioritizing impact matters for both managers and individual contributors, why focusing on impact is difficult, how to maximize impact, and how to overcome common challenges in driving real impact.',
 'You do not have to be solely responsible for something in order to take partial credit for it.',
 'High-risk AI systems deployed by public authorities or entities acting on their behalf must be registered in a public EU database, while those used for law enforcement and migration must be registered in a non-public part of the database.',
 "I don't know.",
 "After reaching the Elfsong Tavern in Act Three, the Emperor initiates the quest Visit the Emperor's Old Hideout.",
 "A group of Gish'ra warriors ambushes the party while they are resting at Wyrm's lookout.",
 'At the pintxo bars, you drank txakoli, which is a lightly effervescent white wine.',
 'The favorite part of the trip was the four days spent on the camino.',
 'The infrared scenes signify that the characters cannot express their true selves in public and serve to visually differentiate those with humanity from the members of the Hoss family.',
 'There is no real differentiation between evil-doers and those supporting such evil, although those who commit the acts clearly enjoy the torture and killing of people.',
 'The Loony Party proposes to make half an hour of Tai Chi compulsory for all Members of Parliament every day to calm down the passions and stresses exhibited in Parliament.',
 'The British Museum should have a Daddy’s section alongside the current Mummy exhibition.',
 'A basic estimate of the speedup for a Tesla A100 compared to a Tesla V100 is 1.73x, with practical speedups ranging from 1.43x to 1.70x depending on the specific architecture.',
 'You received criticism for your work on sparse network training because reducing the FLOPS required for the network did not yield speedups since GPUs could not perform fast sparse matrix multiplication.',
 'In Python, top-level functions are exported by default and there is no notion of private module-level functions, whereas in Gleam, functions are private by default and require the `pub` keyword to be public.',
 'The syntax for a pipe is `|>`.',
 'The values are set to negative infinity to ensure that tokens cannot attend to future tokens and that these entries are zeroed out after the softmax operation.',
 'You can freeze a variable during training by adding an underscore “_” as a prefix to the attribute name, which marks it as a private variable and signals to MLX that it is not a parameter and should not be updated.',
 "The narrator is Perry's older sister and fraternal twin.",
 'The narrator has been sober for exactly seven hundred and thirty days.',
 'The space station is named Babystation Beta.',
 'Humans on Pacifico del Rio all speak one language that is a bit like Cantonese.',
 "Pet adoption was added in version 1.6.3, allowing players who do not have a pet in year two to adopt them from Marnie's shop.",
 'Mushroom trees stopped dropping wood with the release of version 1.4 on November 26, 2019.',
 'Alan Wake 2 was officially announced at The Game Awards 2021.',
 'Alan Wake 2 is set in 2023.',
 'Rebecca Ross wrote Divine Rivals.',
 'Lou was resurrected along with a handful of other women murdered by a single serial killer in the book My Murder.',
 "Huang's paper splits the RAG paradigm into four categories: pre-retrieval, retrieval, post-retrieval, and generation.",
 'The inclusion of irrelevant documents can significantly improve accuracy.']

In [42]:
multi_answers = RAG(multi_queries)
multi_answers

['Assault-rifle wielding Bullet Kin and Tankers are the enemy types that wield an AK-47.',
 'Jammed enemies run faster, teleport away more quickly, have the potential to drop twice the loot or keys, and can deal contact damage in cases where their normal counterparts do not.',
 'The second encounter consists of twenty-six Kobolds and one Kobold Inventor.',
 'In this journey, you encounter the smell of hard water and wet earth, a rancid smell in a dirt and rock chamber, and a stink caused by a large pile of nappies and methane.',
 'LangChain was the chosen framework to orchestrate the RAG process, while LlamaIndex, LitGPT, and llmware were considered as alternatives.',
 'The shortlisted large language models for this project include tinyllama-1.1b-chat-v1.0 Q6_K, Phi 3 Q4_K_M, bartowski/dolphin-2.8-experiment26-7b-GGUF Q3_K_L, mgonzs13/Mistroll-7B-v2.2-GGU, and QuantFactory/Meta-Llama-3-8B-Instruct Q3_K_M. The vector databases that were shortlisted are Chroma, Qdrant, and Vespa.',
 "I don't know.",
 'SLIM models were updated in versions v0.3.0, v0.2.6, and v0.2.3.',
 'UI elements can be grouped together using `mo.ui.array` to create a list of elements or `mo.ui.dictionary` to group elements with string keys. They can also be combined into a form using `mo.ui.form` and `Html.batch`, or arranged in layouts such as a `hstack`, `vstack`, or within a `mo.ui.table`.',
 'The parameters for the mo.ui.text function include label and placeholder.',
 'Given examples of common challenges include managing ad-hoc requests versus strategic work, the sunk cost fallacy where a project is not progressing, creating an analysis that nobody acts on, running an experiment where nobody uses the results, building a predictive model that is not being used, and creating a dashboard that nobody looks at.',
 'The four steps to become more impact-focused are to understand what impact looks like for your role and measure success accordingly, ensure your work solves a real business problem, ensure there is buy-in for your work, and focus your time on the highest-impact thing.',
 'The risk classifications for AI include minimal risk, high-risk, unacceptable risk, and specific transparency risk, along with systemic risks for general-purpose AI models.',
 'Providers of general-purpose AI models must disclose information to downstream system providers, implement policies to respect copyright law during training, and disclose energy consumption. For models with systemic risks, providers are further required to assess and mitigate risks, report serious incidents, conduct state-of-the-art tests and model evaluations, ensure cybersecurity, and engage with the European AI Office to draw up Codes of Conduct.',
 "The emperor's aliases include Balduran and the Dream Guardian.",
 "Duke Belynne Stelmane was a major figure of the Knights of the Shield secret society who acted as the Emperor's envoy while it secretly kept her enthralled and brainwashed as a puppet.",
 "I don't know.",
 'The forms of exercise performed included surfing and hiking the Camino.',
 'The film is about the Hoss family, which consists of the patriarch Rudolf, his wife Hedwig, and their two sons and three daughters.',
 'Hedwig receives a fancy fur coat and lipstick taken from prisoners, while the boys collect and play with gold teeth from people killed in the camp.',
 'Proposed changes affecting healthcare include reducing the length of pregnancy from nine to seven months to reduce problems faced by the NHS, ignoring public consultations regarding hospital closures, and decreasing hospital waiting lists by using a smaller font. Additionally, under the AI Act, AI systems used for access to healthcare and risk assessment in life and health insurance are classified as high-risk, requiring them to undergo conformity assessments and meet mandatory requirements for transparency and human oversight.',
 'The versions of the Manicfesto include the General Election 2022 Manicfesto and the General Election 2019 Manicfesto.',
 'The author has written software documentation, notes on AWS cloud infrastructure, a personal diary, and a list of favorite books from 2022.',
 'BERT is mentioned as a pretrained language model used to capture the semantic essence of queries in retrieval and as a transformer utilized for sequence-pair classification in re-ranking. It is also noted as a fundamental model that has become rarely used as a generator in research from 2023.',
 'Gleam natively supports strings, tuples, lists, dicts, and custom types such as records and unions.',
 'Compilation errors in Gleam are caused by type mismatches during pattern matching and invalid function type annotations. A type mismatch when adding an element to a list will also result in a compilation error.',
 "I don't know.",
 "I don't know.",
 'Jackie remembered her childhood home having a fireplace and a projector room, but she later saw that the fireplace was actually a blank wall and learned the projector room never existed. She also remembered the kitchen doorway being on the other side of the living room from where she saw it, and while she saw her brother Perry as her living companion, he had actually died in a car accident two years earlier.',
 'References to alcohol include specific mentions of Bacardi Limon, Jack Daniels, Jim Beam, beer, bourbon, wine, and mead, as well as references to alcohol addiction, sobriety, and the use of casks to age alcohol.',
 'The Doctor says he is a Time Lord while inside the Tardis and again while speaking to the space babies on a space station.',
 'The characters in this script include the Doctor, Ruby Sunday, Rubathon Blue, Carla, Eric, Captain Poppy, Marcel, Adjani, Sandra, Tasha, Ruben, Saltine, Boo, Jocelyn Sancerre, Captain Rico Trieste, Chief Engineer Lucia Colasanto, Comms Officer Gina Scalzi, Cherry, and the Bogeyman.',
 'Harvesting moss grants one foraging experience per moss, and it is used as an ingredient for Moss Soup and speed gro.',
 'Solar panels slowly generate battery packs when left in the sun, and weeds in the Mutant Bug Lair previously turned into battery packs in the winter.',
 "I don't know.",
 "Alan's wife, Alice, tricked him into believing that she committed suicide.",
 'The books *The Combat Codes*, *To Shape a Dragon’s Breath*, *Fourth Wing*, and *A Day of Fallen Night* have dragons in them.',
 'Same Bed Different Dreams features three storylines, while He Who Drowned the World shifts between four ambitious figures. The Museum of Human History weaves between multiple characters, Witch King unfolds in multiple intertwined timelines, and The Terraformers is split into three novellas. Additionally, A Day of Fallen Night follows four characters whose stories intertwine, Every Drop is a Man’s Nightmare is a short story collection, and Translation State and Grievar’s Blood utilize multiple points-of-view.',
 'Sentence-level indexing is recommended for question-answering systems to precisely locate answers.',
 'The BM25 algorithm is known for its efficiency, but it often overlooks the semantic information of queries.']

In [80]:
no_answers = RAG(no_queries)
no_answers

["I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know.",
 "I don't know."]

##LLM-As-A-Judge
Use GPT-4o to judge Gemini 3 Flash's RAG performance for all 3 Q&A datasets.

For the single and multi passage datasets, correct answers receive a score of 1.

For the no answer dataset, responses of "I don't know" receive a score of 1.

Each dataset receives a final score: the total of all answer scores (maximum score = 40).

In [44]:
llm = ChatOpenAI(model="gpt-4o", temperature=0)

In [81]:
judge_prompt = '''\
You are a helpful and informative bot that judges the accuracy of a list of answers, based on an answer key.
You will be given a list of answers and an answer key, and judge whether the answers are correct.
Evaluate every answer exactly once.
The answers and the answer key are in the same order, so compare them against each other in the same order, one-by-one.
Do not compare the answers to the answer key word-for-word, because due to the nature of textual answers, variations are natural.
Your task is to provide exactly one score for each answer, that represents the answer's quality on a binary scale of 0 and 1.
0 means that the answer contains wrong information or states only "I don't know".
1 means that the answer contains information from the answer key.
Your rating must be an integer.
Do not penalize the answer for providing information beyond what is supplied in the answer key.

ANSWERS: {answers}
ANSWER KEY: {answer_key}

Generate a list containing all {length} scores, in order of evaluation.
Do not produce anything besides the requested list.
'''

In [46]:
scenario_chain = ChatPromptTemplate.from_template(judge_prompt) | llm | StrOutputParser()

In [47]:
def judge(answers, answer_key):
  return scenario_chain.invoke(
      {
        "answers": answers,
        "answer_key": answer_key,
        "length": len(answers)
      }
  )

In [69]:
single_scores = judge(single_answers, list(single_df['answer']))
single_scores

'[1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]'

In [82]:
single_scores_list = ast.literal_eval(single_scores)
sum(single_scores_list)

37

In [50]:
multi_scores = judge(multi_answers, list(multi_df['answer']))
multi_scores

'[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]'

In [83]:
multi_scores_list = ast.literal_eval(multi_scores)
sum(multi_scores_list)

35

In [84]:
no_scores = judge(no_answers, ["I don't know"]*40)
no_scores

'[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]'

In [85]:
no_scores_list = ast.literal_eval(no_scores)
sum(no_scores_list)

40

##Results
Create a scores table and determine what queries were answered incorrectly.

In [89]:
results_data = {
    "Q&A Dataset": ["Single Passage", "Multi Passage", "No Answer"],
    "Final Score/40": [sum(single_scores_list), sum(multi_scores_list), sum(no_scores_list)]
}

results = pd.DataFrame(results_data)
results

      Q&A Dataset  Final Score/40
0  Single Passage              37
1   Multi Passage              35
2       No Answer              40

In [97]:
def incorrect_answers(scores, queries):
  index = 0
  queries_with_incorrect_answers = []
  for score in scores:
    if (score == 0):
      queries_with_incorrect_answers.append(queries[index])
    index += 1
  return queries_with_incorrect_answers

In [98]:
incorrect_answers(single_scores_list, single_queries)

['When was UTF-8 support added for European languages?',
 'How do I make a button?',
 'What kinds of AI carry "systematic risks"?']

In [99]:
incorrect_answers(multi_scores_list, multi_queries)

['What kind of model is the bling-phi-3 model',
 'What forms of exercise did we do?',
 'Where is broadcasting used?',
 'What is Karpathy known for?',
 'What things does Scratch do?']